# Generated by Django 4.1.3 on 2022-12-16 10:23

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp_modules', '0002_post_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 10, 23, 18, 177265)),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7de90f9a-53d9-4442-bcb1-8254c83036c0'), primary_key=True, serialize=False),
        ),
    ]
